[package]
name = "musicbox"
version = "0.1.0"
authors = ["David Gage <whytheplatypus@gmail.com>"]

[dependencies]
tokio-core = "0.1.9"
toml = "0.4.5"

[dependencies.librespot]
git = "https://github.com/plietar/librespot"

[features]
pulseaudio-backend = ["librespot/pulseaudio-backend"]
